wiki/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# TEMPLATE URLS

app_name = 'wiki'

urlpatterns = [
    path('', views.IndexView.as_view(), name='wiki'),
    path('admin/', admin.site.urls),
    path('list/', views.WikiPageListView.as_view(), name='list'),
    path('list/<int:pk>', views.WikiPageDetailView.as_view(), name="detail"),
    path('create/', views.WikiPageCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.WikiPageUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.WikiPageDeleteView.as_view(), name='delete'),
]

wiki_demo/urls.py
from django.contrib import admin
from django.urls import path, include
import wiki

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include('wiki.urls', namespace='wiki')),
    path('', wiki.views.IndexView.as_view(), name='index'),
]

wiki/models.py
from django.db import models
from django.urls import reverse


class WikiPage(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField(max_length=2000)
    links = models.ManyToManyField("wiki.WikiPage", verbose_name="Links")
    counter = models.BigIntegerField(default=0)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("wiki:detail", kwargs={'pk':self.pk})

    @property
    def url(self):
        return self.get_absolute_url()

    @property
    def get_links(self):
        return self.links.all()

wiki/forms.py
from django import forms

class WikiLinkForm(forms.Form):
  title = forms.CharField(max_length=100)

wiki/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import HttpResponse

from . import models


class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'injectme': 'Welcome to the Wiki Demo'})
        return context


class WikiPageListView(ListView):
    model = models.WikiPage
    context_object_name = 'wiki_page_list'
    template_name = "wiki/wiki_page_list.html"


class WikiPageDetailView(DetailView):
    model = models.WikiPage
    context_object_name = 'wiki_page_detail'
    template_name = "wiki/wiki_page_detail.html"

    def get(self, request, *args, **kwargs):
        resp = super(WikiPageDetailView, self).get(request, *args, **kwargs)
        self.object.counter += 1
        self.object.save()
        return resp


class WikiPageCreateView(CreateView):
    model = models.WikiPage
    template_name = "wiki/wiki_page_form.html"
    fields = ('title', 'text', 'links')


class WikiPageUpdateView(UpdateView):
    model = models.WikiPage
    template_name = "wiki/wiki_page_form.html"
    fields = ('title', 'text', 'links')


class WikiPageDeleteView(DeleteView):
    context_object_name = 'wiki_page'
    model = models.WikiPage
    template_name = "wiki/wiki_page_confirm_delete.html"
    success_url = reverse_lazy('wiki:list')

templates/base.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <title>Wiki Demo</title>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'index' %}">Wiki Demo</a>
            <div>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wiki:list' %}">Page List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wiki:create' %}">Create Page</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container pt-5">
            {% block bodyblock %}
            {% endblock %}
        </div>
    </body>

</html>

templates/index.html
{% extends 'base.html' %}
{% block bodyblock %}
    <h1>Wiki Home</h1>
    <h2>{{ injectme }}</h2>
{% endblock %}

wiki/templates/wiki/wiki_page_base.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        {% block headerblock %}
        {% endblock %}
        <title>Wiki Demo</title>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'index' %}">Wiki Demo</a>
            <div>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wiki:list' %}">Pages</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wiki:create' %}">Create</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container pt-5">
            {% block bodyblock %}
            {% endblock %}
        </div>
    </body>

</html>

wiki/templates/wiki/wiki_page_confirm_delete.html
{% extends "wiki/wiki_page_base.html" %}

{% block headerblock %}
    <title>{{ wiki_page.title }}</title>
{% endblock %}

{% block bodyblock %}

<h1>Delete {{ wiki_page.title }}? </h1>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'wiki:detail' pk=wiki_page.pk %}">Cancel</a>
</form>

{% endblock %}

wiki/templates/wiki/wiki_page_detail.html
{% extends "wiki/wiki_page_base.html" %}

{% block headerblock %}
    <title>{{ wiki_page_detail.title }}</title>
{% endblock %}

{% block bodyblock %}

<h2>{{ wiki_page_detail.title }}</h2>
<p>Views: {{ wiki_page_detail.counter }}</p>
<div class="jumbotron">
    <p>{{ wiki_page_detail.text }}</p>
</div>
<div>
    {% if wiki_page_detail.links %}
        {% for wiki_page_link in wiki_page_detail.get_links %}
            <a href={{ wiki_page_link.url }}>{{ wiki_page_link.title }}</a>
        {% endfor %}
    {% endif %}
</div>

<div class="container">
    <p>
        <a class="btn btn-warning" href="{% url 'wiki:update' pk=wiki_page_detail.pk %}">Edit</a>
        <a class="btn btn-warning" href="{% url 'wiki:delete' pk=wiki_page_detail.pk %}">Delete</a>
    </p>
</div>

{% endblock %}

wiki/templates/wiki/wiki_page_form.html
{% extends "wiki/wiki_page_base.html" %}

{% block headerblock %}
    {% if form.instance.pk %}
        <title>{{ form.instance.title }}</title>
    {% endif%}
{% endblock %}

{% block bodyblock %}

<h1>
    {% if not form.instance.pk %}
        Create Wiki Page
    {% else %}
        Update Wiki Page
    {% endif %}
</h1>

<form action="", method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="fieldWrapper">
        <p>
            {{ form.title.errors }}
            <label for="{{ form.title.id_for_label }}">Title</label>
            <br>
            {{ form.title }}
        </p>
    </div>
    <div class="fieldWrapper">
        <p>
            {{ form.text.errors }}
            <label for="{{ form.text.id_for_label }}">Text</label>
            <br>
            {{ form.text }}
        </p>
    </div>
    <div class="fieldWrapper">
        <p>
            {{ form.links.errors }}
            <label for="{{ form.links.id_for_label }}">Links</label>
            <br>
            {{ form.links }}
        </p>
    </div>
    {% comment %} {{ form.as_p }} {% endcomment %}
    <input type="submit" class="btn btn-primary" value="Save">
</form>

{% endblock %}

wiki/templates/wiki/wiki_page_list.html
{% extends "wiki/wiki_page_base.html" %}

{% block bodyblock %}

<h1>Wiki Pages</h1>

{% if not wiki_page_list %}
<h3>There are no wiki pages</h3>
{% else %}
<ol>
    {% for wiki_page in wiki_page_list %}
    <h2><li><a href="{{ wiki_page.id }}">{{ wiki_page.title }}</a></li></h2>
    {% endfor %}
</ol>
{% endif %}

{% endblock %}